// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for LivenessStatusStatus.
const (
	LivenessStatusStatusOk LivenessStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the LivenessStatusStatus enum.
func (e LivenessStatusStatus) Valid() bool {
	switch e {
	case LivenessStatusStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatusStatus.
const (
	ReadinessStatusStatusOk          ReadinessStatusStatus = "ok"
	ReadinessStatusStatusUnavailable ReadinessStatusStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the ReadinessStatusStatus enum.
func (e ReadinessStatusStatus) Valid() bool {
	switch e {
	case ReadinessStatusStatusOk:
		return true
	case ReadinessStatusStatusUnavailable:
		return true
	default:
		return false
	}
}

// LivenessResponse defines model for LivenessResponse.
type LivenessResponse struct {
	Data LivenessStatus `json:"data"`
}

// LivenessStatus defines model for LivenessStatus.
type LivenessStatus struct {
	Status LivenessStatusStatus `json:"status"`
}

// LivenessStatusStatus defines model for LivenessStatus.Status.
type LivenessStatusStatus string

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	Data ReadinessStatus `json:"data"`
}

// ReadinessStatus defines model for ReadinessStatus.
type ReadinessStatus struct {
	// Checks Per-check result, "ok" or "fail".
	Checks map[string]string     `json:"checks"`
	Status ReadinessStatusStatus `json:"status"`
}

// ReadinessStatusStatus defines model for ReadinessStatus.Status.
type ReadinessStatusStatus string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness Liveness probe
	// (GET /healthz)
	Liveness(w http.ResponseWriter, r *http.Request)
	// Readiness Readiness probe
	// (GET /readyz)
	Readiness(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Liveness Liveness probe
// (GET /healthz)
func (_ Unimplemented) Liveness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Readiness Readiness probe
// (GET /readyz)
func (_ Unimplemented) Readiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Liveness operation middleware
func (siw *ServerInterfaceWrapper) Liveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Liveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Readiness operation middleware
func (siw *ServerInterfaceWrapper) Readiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Readiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.Liveness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.Readiness)
	})

	return r
}

type LivenessRequestObject struct {
}

type LivenessResponseObject interface {
	VisitLivenessResponse(w http.ResponseWriter) error
}

type Liveness200JSONResponse LivenessResponse

func (response Liveness200JSONResponse) VisitLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReadinessRequestObject struct {
}

type ReadinessResponseObject interface {
	VisitReadinessResponse(w http.ResponseWriter) error
}

type Readiness200JSONResponse ReadinessResponse

func (response Readiness200JSONResponse) VisitReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Readiness503JSONResponse ReadinessResponse

func (response Readiness503JSONResponse) VisitReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness Liveness probe
	// (GET /healthz)
	Liveness(ctx context.Context, request LivenessRequestObject) (LivenessResponseObject, error)
	// Readiness Readiness probe
	// (GET /readyz)
	Readiness(ctx context.Context, request ReadinessRequestObject) (ReadinessResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Liveness operation middleware
func (sh *strictHandler) Liveness(w http.ResponseWriter, r *http.Request) {
	var request LivenessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Liveness(ctx, request.(LivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Liveness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LivenessResponseObject); ok {
		if err := validResponse.VisitLivenessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Readiness operation middleware
func (sh *strictHandler) Readiness(w http.ResponseWriter, r *http.Request) {
	var request ReadinessRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Readiness(ctx, request.(ReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Readiness")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReadinessResponseObject); ok {
		if err := validResponse.VisitReadinessResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFVPj9vGD/0qxPx+hwSQZadBL7oFQRoskKbGbnOqgooe0dZkpZkpOdLGXfi7FxytvX+8BdIW7Wk1s+Sb",
	"R/Lx+dbYMMTgyScx1a0R29GA+fODm8iTyCVJDF5I7yKHSJwc5YgWE+rf/zNtTWX+t7zHWt4BLY8oVwnT",
	"KOZwKAzTb6Njak31ywzxuTBpH8lUJmy+kE3mUJgneWdvy+me/DgoVLh+ACSJnd+dPXeX9dyDl4St++f1",
	"nmD+asFPE89etx3Z6/yFbeuSCx779aOIJ7UXpiWx7KLGmsqsiRcZBJhk7FMBtQnXtYHAUJstur42pXmG",
	"2rO9LszocULX46anb+58cSzjvAWa4fw25E4/In4VyS62jiWBDT4x2gTSIVMLmz2kjuB9gA3aa/Jtkc+X",
	"pDE3tAGMEdC3elv7H/oxJWIYwsb1pP8r4T15YkzUgg0tgROwYRhc0htN3I3I7fwSwtsLaNltU+1zGWXt",
	"a/82+Im8UpWq9gtYY+oEkAluWGE8OA/bse/hxZv1BejAMEdD7yaC0bfE0CwxuuX0qikgctiQ1B6OvCGO",
	"m95ZmIjd1tmcDBF3NANgykEcQnoJEvJhdyxKYTiMc9GjT6LhzbKBG5e6MCZA2KAQfLr8UCr5dxPx/p4j",
	"/Pjp6mdoyfZaT/N1EYkHJ+KCbypAuD/CNe31sRcNk4SRLZVoFaJ5qfoKniBsoZlLaQpocEydts0qTb2Q",
	"vSQamkJRGnE7T+1i5L4pteuqToGQOuIbJ5S5Xo3WkgiQn6gPkSpobqHOG1abCsqyVIUPdDrCoSnhHXPg",
	"+5z8mqaR3mvgLSilXeB9kSVRwEAiuKMCWkrKowBVNkn61bVwUNTa69641Kug3y3e4hBHgTfrC1OYiVhm",
	"Ha/KV+VKFypE8hidqczrclW+NoWJKhpV/rIj7FP3u37vKJ0vw5rDRDLrgkNugBPg0XvndyV8pIkYUhht",
	"RwItRfIteetIdLVPg71oTXXyWKOrOpte5vDdapUNJ/hEPlPAGPs75S2/iPI4/lR8q/+fXDXv+VlJxzpQ",
	"JV1m95BxGJD3D3jOq6Gdxp2oqTifiD326iYPtWkqMwstAy2ZsN3/eUcvKQZOAjcdqb5ya52XhN4SWPQg",
	"xBNBYtxunT1v48m5/80+nv88PdPIN30PfAyE2Wkhogi1peru+9Xr/5hQgp5QUt7/J8zyTmdij4Z9wv1b",
	"01YonRZrxq0ZuTeVWZrD5xPM0+n/dJwl9nfWW8LHkGbTlY7UgjmMu252WV0vyav3da9S8Djozp+4HT4f",
	"/ggAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
